# implement config for jointgan
DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "jointgan"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "vanilla_relativistic"
  relativistic: True
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
