DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "jointgan.deep_conv"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "least_square_relativistic"
  relativistic: True
  lsgan_disc_fake_target: -1
  lsgan_gen_real_target: -1

OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
